spring:
  application:
    name: mulryuProject
  datasource:
    #  TestDB로 이전 PJT MariaDB 연동
    url: ${MARIA_URI}
    username: ${MARIA_USERNAME}
    password: ${MARIA_PASSWORD}
    driver-class-name: ${MARIA_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      dialect: ${JPA_DIALECT}
      ddl-auto: ${JPA_DDL_AUTO}
  data:
    mongodb:
      uri: ${MONGO_URI}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
    redis: # 0729 DB의 product와 sector 정보를 담기 위한 redis 추가
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}


  security: # 0717 LHJ Spring security를 사용하기 위해 임시로 지정한 name과 password
    user:
      name: ${SECURITY_NAME}
      password: ${SECURITY_PASSWORD}

  rabbitmq: # 0719 LHJ RabbitMQ 연동을 위한 설정파일
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    connection-timeout: 5000
    ssl:
      enabled: true # 기본적으로 Amazon MQ에서는 SSL을 지원하는 브로커로 생성, false로 생성할 시 Error

server: # 0802 서버 포트 변경
  port: 80

logging:
  level:
    root: INFO
    com.ssafy.mulryuproject: DEBUG
springdoc:
  packages-to-scan: com.ssafy.mulryuproject.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8