spring:
  application:
    name: mulryuProject
  datasource:
    url: jdbc:mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S11P12A201?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: S11P12A201@stg-yswa-kr-practice-db-master
    password: WzScD4nJ8f
    driver-class-name: com.mysql.cj.jdbc.Driver
# TestDB로 이전 PJT MariaDB 연동
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
  security: # 0717 LHJ Spring security를 사용하기 위해 임시로 지정한 name과 password
    user:
      name: admin
      password: admin

  rabbitmq: # 0719 LHJ RabbitMQ 연동을 위한 설정파일
    host: 70.12.246.232
    port: 5672
    username: mulryu
    password: mul?ryu201
    virtual-host: /
    connection-timeout: 5000

springdoc:
  packages-to-scan: com.ssafy.mulryuproject.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8